apiVersion: v1
kind: Service
metadata:
  name: app-service-cl
spec:
  type: ClusterIP
  ports:
  - port: 3000
  selector:
    app: application
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-np
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: application
---
apiVersion: v1
kind: Service
metadata:
  name: app-service-lb
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: application
